### ISSUE TITLE
Rekisteröidy labtooliin!

### ISSUE THREAD

**Issue by Kaltsoon** [moversti/drunken-robot#1]
Moikka!

Sovelluksesi näyttää jo todella hyvältä, mutta olet rekisteröitynyt vanhalle kurssille. Rekkaappa tämän periodin kurssille täältä: http://tsoha-labtool.herokuapp.com/register . :)

**Comment by moversti** [comment]
Multa meni sitte varmaan ekan viikon pojot sivu suun? :-P

**Comment by Kaltsoon** [comment]
Ei mennyt, lisään sulle pisteet just nyt. Kiitos muuten pull  
requestista, aina tervetulleita!

- Kalle

Lainaus moversti <notifications@github.com>:
